development:
  adapter: postgresql
  encoding: unicode
  database: graph-tutorial_development
  pool: 5
  username: brad
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: graph-tutorial_test
  pool: 5
  username: brad
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: graph-tutorial_production
  pool: 5
  username: brad
  password:
