development:
  adapter: postgresql
  encoding: unicode
  database: onenote2_development
  pool: 5
  username: brad
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: onenote2_test
  pool: 5
  username: brad
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: onenote2_production
  pool: 5
  username: brad
  password:
