development:
  adapter: postgresql
  encoding: unicode
  database: onenote_development
  pool: 5
  username: brad
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: onenote_test
  pool: 5
  username: brad
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: onenote_production
  pool: 5
  username: brad
  password:
